# Generated by Django 5.1.2 on 2024-12-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectificados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rectificado',
            name='image',
            field=models.ImageField(upload_to='rectificados', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='rectificado',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo'),
        ),
    ]
