# Generated by Django 5.1.2 on 2024-12-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='URLVideo'),
        ),
    ]
