# Generated by Django 5.1.2 on 2024-12-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo'),
        ),
    ]
